CREATE TABLE
IF NOT EXISTS projects
(
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name text NOT NULL CHECK
(name <> ''),
	priority INTEGER NOT NULL,
	descriptiontext,
	deliverydate date NOT NULL
);

CREATE TABLE
IF NOT EXISTS tasks
(
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name text NOT NULL CHECK
(name <> ''),
	done BOOLEAN,
	projectId INTEGER REFERENCES projects
(id)
);

INSERT INTO projects
	(name, priority, description, deliverydate)
VALUES('Make a web App', 1 , 'Using sequelize and postgres', '2020-09-12' );

INSERT INTO projects
	(name, priority, description, deliverydate)
VALUES('Make a desktop App', 1 , 'Using C++', '2020-09-13' );

INSERT INTO projects
	(name, priority, description, deliverydate)
VALUES('Make a mobile App', 1 , 'Using kotlin', '2020-09-18' );


INSERT INTO  tasks
	(name, done, projectId)
VALUES('Download Vuejs', false, 1);

INSERT INTO  tasks
	(name, done, projectId)
VALUES('Create GUI', false, 1);

INSERT INTO  tasks
	(name, done, projectId)
VALUES('Download Android Studio', false, 2);

INSERT INTO  tasks
	(name, done, projectId)
VALUES('Create initial layouts', false, 2);
